version: '2'
services:
  webapp:
    container_name: webapp
    build:
      context: webapp
      dockerfile: Dockerfile
    image: webapp:latest
    ports:
      - 18888:8080
    volumes:
      - webapp-db:/home/node/app
    networks:
      - spring-cloud-network
  patient-service:
    container_name: patient-service
    build:
      context: patient-service
      dockerfile: Dockerfile
    image: patient-service:latest
    ports:
      - 19999:8081
    volumes:
      - patient-service-db:/home/node/app
    networks:
      - spring-cloud-network
  notes-service:
    container_name: notes-service
    build:
      context: notes-service
      dockerfile: Dockerfile
    image: notes-service:latest
    ports:
      - 19999:8082
    volumes:
      - notes-service-db:/home/node/app
    networks:
      - spring-cloud-network
volumes:
networks:
  spring-cloud-network:
    driver: bridge