version: '2'
services:
  webapp:
    container_name: webapp
    build:
      context: webapp
      dockerfile: Dockerfile
    image: webapp:latest
    ports:
      - 18888:8080
    networks:
      - spring-cloud-network
  patient-service:
    container_name: patient-service
    build:
      context: patient-service
      dockerfile: Dockerfile
      extra_hosts:
        host.docker.internal:127.0.0.1
    image: patient-service:latest
    ports:
      - 19999:8081
    networks:
      - spring-cloud-network
networks:
  spring-cloud-network:
    driver: bridge