version: '2'
services:
  mysql-server:
    restart: always
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD:test_pass # TODO: Change this
      - MYSQL_USER:springuser
      - MYSQL_PASS:ThePassword
    volumes:
      - mysql-data:/var/lib/mysql
  mongodb-server:
    restart: always
    image: mongo:latest
    volumes:
      - mongodb-data:/data/db
  webapp:
    build:
      context: webapp
      dockerfile: "./Dockerfile"
    #    image: webapp:latest
    ports:
      - 18888:8080
    environment:
      - SPRING_PROFILES_ACTIVE=docker
  #    networks:
  #      - spring-cloud-network
  patient-service:
    build:
      context: patient-service
      dockerfile: "./Dockerfile"
    #    image: patient-service:latest
    ports:
      - 17777:8081
    environment:
      - SPRING_PROFILES_ACTIVE=docker
  #    networks:
  #      - spring-cloud-network
  notes-service:
    build:
      context: notes-service
      dockerfile: "./Dockerfile"
    #    image: notes-service:latest
    ports:
      - 19999:8082
    environment:
      - SPRING_PROFILES_ACTIVE=docker
  #   networks:
  #     - spring-cloud-network
  risk-service:
    build:
      context: risk-service
      dockerfile: "./Dockerfile"
    #    image: notes-service:latest
    ports:
      - 19999:8083
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    #   networks:
    #     - spring-cloud-network

volumes:
  mysql-data:
  mongodb-data:

#networks:
#  spring-cloud-network:
#   driver: bridge