version: '2'
services:
  mysql-server:
    restart: always
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD:test_pass
      - MYSQL_USER:springuser
      - MYSQL_PASS:ThePassword
    volumes:
      - mysql-data:/var/lib/mysql
  mongodb-server:
    restart: always
    image: mongo:latest
    volumes:
      - mongodb-data:/data/db

  webapp:
    build:
      context: webapp
      dockerfile: "./Dockerfile"
    ports:
      - 18888:8080
    environment:
      - SPRING_PROFILES_ACTIVE=docker

  patient-service:
    build:
      context: patient-service
      dockerfile: "./Dockerfile"
    ports:
      - 17777:8081
    environment:
      - SPRING_PROFILES_ACTIVE=docker

  notes-service:
    build:
      context: notes-service
      dockerfile: "./Dockerfile"
    ports:
      - 19999:8082
    environment:
      - SPRING_PROFILES_ACTIVE=docker

  risk-service:
    build:
      context: risk-service
      dockerfile: "./Dockerfile"
    ports:
      - 16666:8083
    environment:
      - SPRING_PROFILES_ACTIVE=docker

volumes:
  mysql-data:
  mongodb-data:
